# Generated by Django 4.2.23 on 2025-07-17 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
